### ISSUE TITLE
4.5.0-0.okd-2020-06-29-110348-beta6

### ISSUE THREAD

**Issue by disposab1e** [cgruver/okd4-upi-lab-setup#9]
Just to let you know... no success with following combinations:

4.5.0-0.okd-2020-06-29-110348-beta6
stable/32.20200615.3.0
stable/32.20200601.3.0
stable/31.20200517.3.0
next/32.20200625.1.0

4.5.0-0.okd-2020-06-30-142627
stable/32.20200615.3.0

4.6.0-0.okd-2020-06-29-123105
stable/32.20200615.3.0
next/32.20200625.1.0

To be honest I don't think it's an CoreOS issue.

**Comment by cgruver** [comment]
I have not been able to get 4.5 and FCOS 32 to work yet either. 
I added a note to my README.
The Deploy script also has a 4.4 specific variable,  which I have fixed in a branch, but the 4.5 issues seem to related to FCOS 32.

I'll update you if I have any breakthrough this weekend.   It's a holiday here in the states.
Sent from Yahoo Mail on Android 
 
  On Wed, Jul 1, 2020 at 2:10, disposab1e<notifications@github.com> wrote:   


Just to let you know... no success with following combinations:

4.5.0-0.okd-2020-06-29-110348-beta6
stable/32.20200615.3.0
stable/32.20200601.3.0
stable/31.20200517.3.0
next/32.20200625.1.0

4.5.0-0.okd-2020-06-30-142627
stable/32.20200615.3.0

4.6.0-0.okd-2020-06-29-123105
stable/32.20200615.3.0
next/32.20200625.1.0

**Comment by cgruver** [comment]
This should fix the issue.  You will have to build from a 4.5 nightly.  Beta 6 will not have this fix.

https://github.com/openshift/machine-config-operator/pull/1889

**Comment by disposab1e** [comment]
Cool! Thx!

Works with:
4.5.0-0.okd-2020-07-02-203357
stable/32.20200615.3.0

Just change in image pruner from: 
"*/0 * * * *" 
to 
"0 0 * * *" 
than error disappears.

Tested with Rook: 1.3.7 ... just copy and paste new manifests and apply your changes.

4.6.0-0.okd-2020-07-01-233221
still not working

**Comment by cgruver** [comment]
Yeah, I fixed that image pruner in my docs a couple days ago.  I got bad syntax from an old version of the documentation.

4.6 probably won't be working for a while.  It is a new branch being developed.  OCP 4.5 will be GA soon.  OKD 4 GA will be based on 4.5.

**Comment by ashaver** [comment]
Where exactly (or how) do I change the image pruner?

**Comment by cgruver** [comment]
This is the link to the OCP 4.4 docs, should be the same for 4.5:

https://docs.openshift.com/container-platform/4.4/registry/configuring-registry-operator.html

It is a custom resource.  The one created by default is named `cluster`

You can patch it with a schedule like this:  (Runs every day at midnight.)

```
oc patch imagepruners.imageregistry.operator.openshift.io/cluster --type merge -p '{"spec":{"schedule":"0 0 * * *","suspend":false,"keepTagRevisions":3,"keepYoungerThan":60,"resources":{},"affinity":{},"nodeSelector":{},"tolerations":[],"startingDeadlineSeconds":60,"successfulJobsHistoryLimit":3,"failedJobsHistoryLimit":3}}'
```

Or use `cron` syntax to set your own schedule.

**Comment by disposab1e** [comment]
This is exactly [what I did](https://github.com/disposab1e/okd-lab/blob/master/ansible/okd/roles/infrastructure/tasks/main.yml)!

**Comment by cgruver** [comment]
Closing this.
